#Run for Docker

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Expose only specific actuator endpoints (health and info) via the web
management.endpoints.web.exposure.include=health,info

# Hide detailed health information to prevent exposing sensitive data
management.endpoint.health.show-details=never

management.prometheus.metrics.export.enabled=true
management.metrics.enable.processor=false

spring.liquibase.change-log=classpath:db/changelog/master.yaml
spring.liquibase.enabled=true

#Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

spring.security.oauth2.client.provider.keycloak.issuer-uri=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_NAME_ATTRIBUTE}

spring.security.oauth2.client.registration.keycloak.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.scope=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE}
#logging.level.org.springframework.security=DEBUG