### localhost or keycloak
POST http://localhost:8080/realms/my-realm-project/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=springsecurity&client_secret=Zqbwmc2pqW5IPZ93GmrPAbEC3CPa2PJ1&username=alex.tru25&password=password&grant_type=password
