name: news-system

services:
  # Существующий микросервис news-parser
  app:
    build:
      context: ../..
      dockerfile: common-services/kafka/Dockerfile
    image: news-parser:latest
    container_name: ms-parser
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/news
      SPRING_DATASOURCE_USERNAME: aleksandrtufanov
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - postgres
      - kafka

  # Существующая база данных PostgreSQL
  postgres:
    image: postgres:17.4
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aleksandrtufanov
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: news
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all", "-c", "wal_level=logical", "-c", "max_replication_slots=4"]

  # Добавляем Zookeeper для Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Добавляем Kafka
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 5000
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 29092"]
      interval: 10s
      timeout: 5s
      retries: 10

  init-kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: debezium_init_kafka
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    volumes:
      - ./etc/docker/kafka/init-kafka-topics.sh:/init-kafka-topics.sh
    command: /init-kafka-topics.sh

  # Добавляем Kafka UI для мониторинга
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka_ui
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: news
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  # Добавляем Kafka Connect с Debezium
  kafka-connect:
    build:
      context: /Users/aleksandrtufanov/IdeaProjects/news-parser
      dockerfile: common-services/kafka/Dockerfile
      args:
        JMX_AGENT_VERSION: 0.17.2
    container_name: debezium_connect
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "1976:1976"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=kafka_connect_configs
      - OFFSET_STORAGE_TOPIC=kafka_connect_offsets
      - STATUS_STORAGE_TOPIC=kafka_connect_statuses
      - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
      - JMXHOST=localhost
      - JMXPORT=1976
    healthcheck:
      test: [ "CMD-SHELL", "curl -sSf http://localhost:8083/connectors || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  # Добавляем Prometheus
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: debezium_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      kafka-connect:
        condition: service_healthy
    volumes:
      - ./etc/docker/debezium-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # Добавляем Grafana
  grafana:
    build:
      context: ./etc/docker/debezium-grafana
    container_name: debezium_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DS_PROMETHEUS=prometheus